#!/usr/bin/env python

import os, sys
import subprocess
from subprocess import check_call

sys.argv[0] = os.path.abspath(sys.argv[0])
sys.argv[1] = os.path.abspath(sys.argv[1])
print("ScriptTestingJason: path0 " + sys.argv[0])
print("ScriptTestingJason: path1 " + sys.argv[1])

editor_path = os.path.split(sys.argv[0])[0]
print("ScriptTestingJason: editor_path " + editor_path)

file_list = os.listdir(editor_path)

file_list.sort()

for f in file_list:
    if f.lower().startswith('postprocessbuildplayer_'):
        pathName = os.path.join(editor_path, f)
        fileName, fileExtension = os.path.splitext(pathName)

        if not fileExtension == '.meta' and os.path.isfile(pathName): #ignore meta files
            print("ScriptTestingJason: script path " + pathName)
            sys.argv[0] = pathName
            try:
                check_call(sys.argv)
            except Exception, e:
                print("script: " + pathName + " failed")
